name: Build and Deploy Clariolane 

on:
  push:
    tags: [ 'release/v*.*.*' ]
    # branches: [ "**" ]  # Uncomment this line to test in your feature branch
    # branches: ["clario-deployment"]

jobs:
  # JOB 1: Build the application
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build The App
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_PAYSTACK_PUBLIC_KEY: ${{ secrets.VITE_PAYSTACK_PUBLIC_KEY }}

      # Save the 'dist' folder so the next job can use it
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist/

  # JOB 2: Deploy to Server
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy only runs if build succeeds
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist/

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }} # e.g., your_server_public_ip
          username: ${{ secrets.SERVER_USER }} # e.g., ubuntu or root
          key: ${{ secrets.SERVER_SSH_KEY }} # The private SSH key of the user
          source: "dist/*"
          target: "/var/www/html"
          strip_components: 1 

      - name: Post-deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            systemctl reload nginx
            echo "Deployment successful to Digital Ocean"
